version: '3.8'

services:
  eureka-server:
    build:
      context: ./EurekaServerService
      dockerfile: Dockerfile
    ports:
      - "9099:9099"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  config-server:
    build:
      context: ./CloudConfig
      dockerfile: Dockerfile
    ports:
      - "9296:9296"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "9050:9050"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - config-server

  product-service:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    ports:
      - "9051:9051"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - config-server

  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "9052:9052"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - config-server

  payment-service:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    ports:
      - "9053:9053"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - config-server

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - config-server