version: '3.8'

services:
  eureka-server:
    build: ./EurekaServerService
    ports:
      - "9099:9099"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PORT=9099

  config-server:
    build: ./CloudConfig
    ports:
      - "9296:9296"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - PORT=9296
    depends_on:
      - eureka-server

  user-service:
    build: ./UserService
    ports:
      - "9050:9050"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - PORT=9050
    depends_on:
      - eureka-server
      - config-server

  product-service:
    build: ./ProductService
    ports:
      - "9051:9051"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - PORT=9051
    depends_on:
      - eureka-server
      - config-server

  order-service:
    build: ./OrderService
    ports:
      - "9052:9052"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - PORT=9052
    depends_on:
      - eureka-server
      - config-server

  payment-service:
    build: ./PaymentService
    ports:
      - "9053:9053"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - PORT=9053
    depends_on:
      - eureka-server
      - config-server

  api-gateway:
    build: ./ApiGateway
    ports:
      - "9191:9191"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:9099/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9296
      - PORT=9191
    depends_on:
      - eureka-server
      - config-server