services:
  # Eureka Server
  - type: web
    name: eureka-server
    env: java
    buildCommand: cd EurekaServerService && ./mvnw clean package -DskipTests
    startCommand: cd EurekaServerService && java -jar target/EurekaServerService.jar
    plan: starter
    envVars:
      - key: SERVER_PORT
        value: 9099
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # Config Server
  - type: web
    name: config-server
    env: java
    buildCommand: cd CloudConfig && ./mvnw clean package -DskipTests
    startCommand: cd CloudConfig && java -jar target/CloudConfig.jar
    plan: starter
    envVars:
      - key: SERVER_PORT
        value: 9296
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://eureka-server.onrender.com/eureka
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # User Service
  - type: web
    name: user-service
    env: java
    buildCommand: cd UserService && ./mvnw clean package -DskipTests
    startCommand: cd UserService && java -jar target/UserService.jar
    plan: starter
    envVars:
      - key: SERVER_PORT
        value: 9050
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://eureka-server.onrender.com/eureka
      - key: SPRING_CLOUD_CONFIG_URI
        value: https://config-server.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # Product Service
  - type: web
    name: product-service
    env: java
    buildCommand: cd ProductService && ./mvnw clean package -DskipTests
    startCommand: cd ProductService && java -jar target/ProductService.jar
    plan: starter
    envVars:
      - key: SERVER_PORT
        value: 9051
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://eureka-server.onrender.com/eureka
      - key: SPRING_CLOUD_CONFIG_URI
        value: https://config-server.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # Order Service
  - type: web
    name: order-service
    env: java
    buildCommand: cd OrderService && ./mvnw clean package -DskipTests
    startCommand: cd OrderService && java -jar target/OrderService.jar
    plan: starter
    envVars:
      - key: SERVER_PORT
        value: 9052
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://eureka-server.onrender.com/eureka
      - key: SPRING_CLOUD_CONFIG_URI
        value: https://config-server.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # Payment Service
  - type: web
    name: payment-service
    env: java
    buildCommand: cd PaymentService && ./mvnw clean package -DskipTests
    startCommand: cd PaymentService && java -jar target/PaymentService.jar
    plan: starter
    envVars:
      - key: SERVER_PORT
        value: 9053
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://eureka-server.onrender.com/eureka
      - key: SPRING_CLOUD_CONFIG_URI
        value: https://config-server.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # API Gateway
  - type: web
    name: api-gateway
    env: java
    buildCommand: cd ApiGateway && ./mvnw clean package -DskipTests
    startCommand: cd ApiGateway && java -jar target/ApiGateway.jar
    plan: starter
    envVars:
      - key: SERVER_PORT
        value: 9191
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://eureka-server.onrender.com/eureka
      - key: SPRING_CLOUD_CONFIG_URI
        value: https://config-server.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: starter